name: Mobile Tests

on:
  push:
    branches: ["ci"]
  workflow_dispatch:

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci

      - name: Executar testes
        env:
          ENVIRONMENT: saucelabs
          PLATFORM: ios
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test:login